### ISSUE TITLE
Wind layer

### ISSUE THREAD

**Issue by Saltallica** [skepticalmartyr/PaperGorillas#1]
The original gorillas had "wind" - this had to be taken in to account when a player launched a banana and it would affect the trajectory. The game displayed this by showing an arrow on the screen pointing to the left or right showing the direction of the wind, and the length of the arrow represented the force. I think we can come up with something a little more interesting in our version.

 I propose having a background layer that instead has dynamically created clouds that move in the direction and speed of the wind. When a cloud leaves the viewport, it is removed and a new cloud is created.

**Comment by skepticalmartyr** [comment]
I like the idea of having the clouds show the direction and speed of the wind based on how they move across the screen. Which approach makes the most sense to create the clouds? (Draw white circles of varying sizes and intersecting them to make a cloud shape, draw the cloud in Illustrator?)
