### ISSUE TITLE
Map is missing text, appears to have some weird div overlap

### ISSUE THREAD

**Issue by Saltallica** [skepticalmartyr/PaperGorillas#124]

**Comment by Saltallica** [comment]
![image](https://user-images.githubusercontent.com/1064853/58370986-12365900-7edb-11e9-9e75-44821778bc33.png)

**Comment by Saltallica** [comment]
note the gray transparent square on the left edge

**Comment by skepticalmartyr** [comment]
Gray div belonged to save slots. just moved it to the left a bit more when it is "closed". What is the "missing text"? If you are referring to "1 Player..." at the top, I decided to hide that because one can appreciate the map more. at that point one already knows they are in single player mode.
