### ISSUE TITLE
Multiplayer select 2 or 4 players: Keyboard focus/highlighting makes for confusing selection process 

### ISSUE THREAD

**Issue by Saltallica** [skepticalmartyr/PaperGorillas#141]
The keyboard selection should not take precedence visually over the currently selected number of players - it makes it hard to know which one is actually selected.

**Comment by skepticalmartyr** [comment]
Can you be more specific? Not sure what you're talking about here.

**Comment by skepticalmartyr** [comment]
How about changing the color to gold for keynav selection on 2-4 player? b60b669c13f968c80d2e4ccbf455be3bff5c41f2

**Comment by skepticalmartyr** [comment]
How about d035ad768f5343bda2b9f748ccb64d75d99ac5dd
