### ISSUE TITLE
Multiplayer: Dim/fade other players powerups when it's your turn

### ISSUE THREAD

**Issue by Saltallica** [skepticalmartyr/PaperGorillas#143]
It can be confusing, switching from single player to multiplayer that there are powerups on both sides of the screen. Need to make it obvious which ones are accessible to the current player.

**Comment by Saltallica** [comment]
Also, shouldn't be able to hover / appear as though they are selectable via mouse if they are not the current players.

**Comment by Saltallica** [comment]
Will make some adjustments to this - the notification animation is jarring, and I notice some of the powerups for the current player are faded out even though they can be used

**Comment by skepticalmartyr** [comment]
Tweaked styles with 73e95e06
