### ISSUE TITLE
multiplayer: gamepad powerup selection logic in use when there are no gamepads

### ISSUE THREAD

**Issue by Saltallica** [skepticalmartyr/PaperGorillas#147]
Noticed while playing that some of the powerups are displayed as faded out, this appears to be because some have a "selected" class, while others do not. I assume this is because you can switch back and forth between powerups via the gamepad, and you want to know which one is selected.

Some issues:

- This behavior is only relevant when the player is using a gamepad. Any gamepad relevant logic should be disabled UNLESS a gamepad is detected. 

- I noticed that sometimes there were two items with the "selected" class.

- When a gamepad is detected and in use, the graying or fading out of non selected powerups is confusing because we also use that visual treatment for powerups that can't be used. Instead of doing a subtractive selection design, do an additive: scale the selected icon up by 10%, or add a text-shadow glow around it, and leave the other powerups as is.

**Comment by skepticalmartyr** [comment]
Fixed with 404cfe133f4db20dca8efb03182d291f9c0493e5

**Comment by Saltallica** [comment]
Not quite:

![image](https://user-images.githubusercontent.com/1064853/67147456-f608cf00-f262-11e9-8a0f-21d055e20bc1.png)

It appears some of the icons show as yellow for some reason.

I am reassigning to myself to look at.

**Comment by Saltallica** [comment]
Ok, fixed via:

https://github.com/skepticalmartyr/PaperGorillas/commit/a8ff597f337a0285239a8112c30550fe131af072

and

https://github.com/skepticalmartyr/PaperGorillas/commit/b7111552ec9749a90564999d034851928ed426d4
