### ISSUE TITLE
Keyboard control: no repeated decrement on angle or velocity via keyboard with low sensitivty

### ISSUE THREAD

**Issue by Saltallica** [skepticalmartyr/PaperGorillas#149]
While playing multiplayer I stumbled in to a scenario:

Had my sensitivity at about the halfway mark in game and wasn't happy with not having fine control over angle, was increasing/decreasing values by like 7.

Change sensitivity to a low amount

I could still increase angle and velocity by holding down the up and right arrow keys, but decreasing either by holding the left or down arrows only resulted an a decrement of one, and no further change. So, you would have to tap the key every time to move a single amount - which was tedious.

We may need to re-investigate how we do sensitivity altogether: instead of increasing or decrease the amount we increment, we could instead change the update rate/throttle on the keydown/keyup - similar to the throttling in place on the main screen.

**Comment by skepticalmartyr** [comment]
Looking into this.

**Comment by skepticalmartyr** [comment]
Tested on my end in both single and multiplayer. Holding down the left and down arrow keys continuously decreases the velocity/angle. I even set my sensitivity to the lowest value and it still worked.

**Comment by Saltallica** [comment]
Fixed via research-input-sensitivity branch
