### ISSUE TITLE
4 player: powerups not assigning to correct players

### ISSUE THREAD

**Issue by Saltallica** [skepticalmartyr/PaperGorillas#162]
Several times during play testing last night, powerups were not assigned to the correct player after hitting blimps. As player 1 - I would hit a blimp and would not see a power up adding to the slot in the left side of the screen, I don't know if this is because once the hit occurs we switch the slots to a different player, if a different player was awarded the power up.

**Comment by skepticalmartyr** [comment]
The power ups toggle to the next player on your team when your turn is over. If this is a problem, I guess we could toggle the power ups based on when the turn queue gets updated. So, if you hit a blimp and get a powerup, your powerups will stay on the screen until it's your teammate's turn. Then, we could toggle the powerups again to show the current player's. Or, we could make powerups a combined team thing and not mess with this toggling business.

**Comment by skepticalmartyr** [comment]
Think we're good now with powerups being shared by team members
