### ISSUE TITLE
2 player: steambot bell ding sound position

### ISSUE THREAD

**Issue by Saltallica** [skepticalmartyr/PaperGorillas#163]
It appears that when playing as steambot, that the bell ringing sound always comes from the right speaker even when the player is on the left side of the screen - investigate and fix?

**Comment by skepticalmartyr** [comment]
Fixed part of the issue with ba8fcd0b

Other problem is that the player position returns 0, 0 randomly, causing sound to be played from the middle.

**Comment by Saltallica** [comment]
I "fixed" (hacked) the 0,0 issue by just caching the last X,Y values we explicitly set in the X and Y setters. Then, in the calls where this keeps happening, we just use the cachedX and cachedY values. Ideally we should reach point out the issue to the pixi.spine repo owner - and then upgrade our pixi spine runtime, but ain't nobody got time for that.

https://github.com/skepticalmartyr/PaperGorillas/commit/4b158626b975e0480425e3935732b5ae1c93ca80
