### ISSUE TITLE
audiosprite API

### ISSUE THREAD

**Issue by skepticalmartyr** [skepticalmartyr/PaperGorillas#20]
https://github.com/tonistiigi/audiosprite

Can you give me some direction on this? I understand it at a very high-level but I'm not sure how I use this in the real world. The documentation is sparse.

**Comment by Saltallica** [comment]
Looking over it, it appears you take your individual mp3 files, pass them
to through the command line tool, and it outputs a combined file, along
with a JSON file describing where the start and end of each sound is in the
resulting combined file.

This will require some experimentation on your end to get the appropriate
output you want. Good luck!
