### ISSUE TITLE
Refactor cityscape building construction / damage buildings code

### ISSUE THREAD

**Issue by Saltallica** [skepticalmartyr/PaperGorillas#26]
It's crap, and it needs to be reorganized so a building is a single cohesive unit.

**Comment by Saltallica** [comment]
Had an epiphany - going to take the new background buildings, aka, DecoBuilding, and make them the interactive buildings, and have a simplified background background buildings

**Comment by skepticalmartyr** [comment]
I look forward to seeing what you come up with.
