### ISSUE TITLE
Sound Requirements!

### ISSUE THREAD

**Issue by Saltallica** [skepticalmartyr/PaperGorillas#3]
The explosion is a good start, but it doesn't allow for overlapping sounds - this is a common issue with the html5 audio tag. 

We'll also need that sound expanded a bit, it need to have a bit more "depth" to it. It needs to echo as though it's bouncing off buildings and you are hearing it from a distance, it also needs the sound of glass shattering, and finally, the sound of rubble hitting the ground. I'm sure you can mix something together to give a pretty convincing effect.

We'll also need the sound of wind, in a continuous -- and convincing -- loop.

Also, a sound for when the banana is flipping through the air - like a whooshing sound. "wooshwooshwooshwooshwoosh". That needs to repeat seamlessly until it hits a target.

Even cooler would be some sort of low sounding city sounds, like traffic and sirens off in the distance.

To orchestrate all of this, we'll need to include an actual javascript sound library to manage playing all of these things together.

Please learn and integrate howler.js for managing all the sounds:

http://goldfirestudios.com/blog/104/howler.js-Modern-Web-Audio-Javascript-Library

You'll also want to wrap all this into a separate module for playing sounds like we did with TextAdventure.

**Comment by skepticalmartyr** [comment]
The explosion is a good start, but it doesn't allow for overlapping sounds - this is a common issue with the html5 audio tag. 
**Complete**

We'll also need that sound expanded a bit, it need to have a bit more "depth" to it. It needs to echo as though it's bouncing off buildings and you are hearing it from a distance, it also needs the sound of glass shattering, and finally, the sound of rubble hitting the ground. I'm sure you can mix something together to give a pretty convincing effect.
**Complete**

We'll also need the sound of wind, in a continuous -- and convincing -- loop.
**Work in progress**

Also, a sound for when the banana is flipping through the air - like a whooshing sound. "wooshwooshwooshwooshwoosh". That needs to repeat seamlessly until it hits a target.
**Complete**

Even cooler would be some sort of low sounding city sounds, like traffic and sirens off in the distance.
**Still have to do**

To orchestrate all of this, we'll need to include an actual javascript sound library to manage playing all of these things together.

Please learn and integrate howler.js for managing all the sounds:

http://goldfirestudios.com/blog/104/howler.js-Modern-Web-Audio-Javascript-Library

You'll also want to wrap all this into a separate module for playing sounds like we did with TextAdventure
****Complete
