### ISSUE TITLE
Get click to set sound working

### ISSUE THREAD

**Issue by skepticalmartyr** [skepticalmartyr/PaperGorillas#49]
I will see if the code below works tonight.

$(document).mousedown(function(e){

	if (e.target.className !== "fader" && e.target.className === "fader-box") {
  	
		let sliderBox = $("." + e.target.className);
               
		let slider = $("." + e.target.className).children(".fader");

		let pos = (e.offsetX / slider.outerWidth()) * 100;

		slider.animate({left: pos + "%"}, 200);
    
   }

});

**Comment by Saltallica** [comment]
You'll want to tweak it a little bit. Outerwidth/width doesn't take in to
account scaling on the outer div, that's why I changed the other code to
use that "get client bounds" call.

**Comment by skepticalmartyr** [comment]
`$(document).mousedown(function(e) {
  
    if (e.target.className !== "fader" && e.target.className === "fader-box") {

        let sliderBox = $("." + e.target.className);

        let slider = $("." + e.target.className).children(".fader");

        let pos = (e.offsetX / sliderBox[0].getBoundingClientRect().width) * 100;

        slider.animate({
            left: pos + "%"
        }, 500);

    }

});`

**Comment by skepticalmartyr** [comment]
Actually, changing the handler to mousedown seemed to do the trick. If you click inside the fader it will stay where it is and you can still drag it. If you click outside of the fader, it will slide as expected.
