### ISSUE TITLE
Inception Bug - Gorilla not positioned on building top

### ISSUE THREAD

**Issue by skepticalmartyr** [skepticalmartyr/PaperGorillas#53]
<img width="138" alt="screen shot 2017-06-01 at 7 45 16 pm" src="https://cloud.githubusercontent.com/assets/13459311/26705284/42e2b042-4703-11e7-8cb4-ad3f14fcbd23.png">
<img width="154" alt="screen shot 2017-06-01 at 7 46 20 pm" src="https://cloud.githubusercontent.com/assets/13459311/26705283/42dd873e-4703-11e7-9ab1-c763598d3911.png">
<img width="1042" alt="screen shot 2017-06-01 at 7 47 08 pm" src="https://cloud.githubusercontent.com/assets/13459311/26705285/42e6c0d8-4703-11e7-8085-99ceb700c677.png">

Tested various powerups. Gorilla is not positioned on building tops consistently with Inception.

**Comment by skepticalmartyr** [comment]
This appears to happen after the gorilla's position has been altered with Shrink or Teleport.

**Comment by Saltallica** [comment]
@skepticalmartyr  Can you confirm, is this with the left gorilla only, or both?

**Comment by skepticalmartyr** [comment]
Both. 
<img width="507" alt="screen shot 2017-06-04 at 3 11 53 pm" src="https://cloud.githubusercontent.com/assets/13459311/26764632/356d5ce6-4938-11e7-8eea-3c51789907e2.png">
