### ISSUE TITLE
Don't allow gorilla to teleport to building that's already occupied

### ISSUE THREAD

**Issue by skepticalmartyr** [skepticalmartyr/PaperGorillas#54]

**Comment by skepticalmartyr** [comment]
root cause was in the checkBounds method. b.frame.children[2].width was not valid. changed to b.frame.children[2].getBounds().width. After fixing that I had to change b.getBounds().right to b.frame.children[2].getBounds().right on line 257. This caused the gorillas to be placed on the wrong side. Flipped the sign from < to > and it seems to work now.. Gorillas should not teleport on already occupied buildings.

**Comment by skepticalmartyr** [comment]
gorillas were not being positioned correctly. reverted the changes..

**Comment by Saltallica** [comment]
I guess the question is.. how incorrectly?

**Comment by skepticalmartyr** [comment]
Gorillas were placed on the same building

**Comment by skepticalmartyr** [comment]
This is still happening.

<img width="95" alt="screen shot 2017-07-15 at 3 02 08 pm" src="https://user-images.githubusercontent.com/13459311/28242016-b500f6e2-696e-11e7-88f7-c29bf97923e3.png">

**Comment by skepticalmartyr** [comment]
This is fixed.
