### ISSUE TITLE
GPU Memory Leak

### ISSUE THREAD

**Issue by Saltallica** [skepticalmartyr/PaperGorillas#59]
Under chrome /modes/remote, GPU Memory increases 1-2 mb about every 5 seconds, while the game is idle. This eventually grows to consume all available GPU memory and the game slows down 20-30 fps.

To reproduce, just go to modes/remote, and open up the task manager in Chrome and keep an eye on the GPU memory, you'll notice it steadily climbing, this is while nothing in the game is occuring except new blimps being generated.

**Comment by skepticalmartyr** [comment]
I do not have this issue on my laptop. The GPU memory is steady.

**Comment by skepticalmartyr** [comment]
**Specifications**
Processor: 2.5 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Graphics: NVIDIA GefORCE gt 750m 2048 MB Intel Iris Pro 1536 MB

# GPU Memory Usage Over One Hour and FPS
10:36 AM - 362 MB, 60 FPS
10:46 AM - 363 MB, 60 FPS
11:03 AM - 315 MB, 60 FPS
11:24 AM - 324 MB, 60 FPS
11:36 AM - 329 MB, 60 FPS

**Comment by skepticalmartyr** [comment]
Memory leak issues appear to be addressed in Chrome 65.0.3325.146. Issue doesn't occur with this version.
