### ISSUE TITLE
Code for tracking player accuracy

### ISSUE THREAD

**Issue by Saltallica** [skepticalmartyr/PaperGorillas#74]
Some thoughts on this while I'm not super tired:

Accuracy for two player mode can be determined how close a banana got to the opposing gorilla.  The accuracy can be represented as:

(Starting Distance - Closest distance from gorilla) / Starting Distance from gorilla 

So, if starting distance is say, 500 "feet", and we got within 50 feet of the other gorilla:

(500 - 50) / 500  
= 450 / 500 
= 0.9
= 90%

Likewise, if we throw and we barely go anywhere and hit a building instead

(500 - 400) / 500
= 100 / 500
= 0.2
= 20%

what about if we throw backwards or wind carries our banana in the opposite direction? We also need to track the FURTHEST point the banana got from the other gorilla

In which case, we swap out the fixed distance between the gorilla and the maximum distance

(new MAX distance - closest) / new Max Distance

(1000 - 500) / 1000

= 2 / 1000
= 0.02%
= terrible, terrible throw

A hit, of course, would be 100% accuracy.

To get the ending accuracy, we get an average of all the prior computed accuracies: So, let say

(20% + 1% + 90% + 100%) / 4

(211% / 4)

round(52.75%)

53%

Or do we want to do median?

Magic(1%, 20%, 90%, 100%) = 55%

**Comment by skepticalmartyr** [comment]
This could work. Let's go with the average. If the total length of the set is odd, the median is just the middle number. That doesn't tell us much about good the player is. 
1, 3, 90.   The median is 3

**Comment by Saltallica** [comment]
Truth, average it is.
