### ISSUE TITLE
Single Player: Use of Inception breaks the game

### ISSUE THREAD

**Issue by skepticalmartyr** [skepticalmartyr/PaperGorillas#86]
when inception is used in single player mode, 
<img width="627" alt="screen shot 2017-08-27 at 7 23 22 pm" src="https://user-images.githubusercontent.com/13459311/29754925-3b33c8f6-8b5d-11e7-83f2-58e11da03230.png">

**Comment by Saltallica** [comment]
I've seen this as well

**Comment by skepticalmartyr** [comment]
<img width="315" alt="screen shot 2017-08-29 at 7 31 50 pm" src="https://user-images.githubusercontent.com/13459311/29848760-c14545ca-8cf0-11e7-8763-e12e8b8aef70.png">
