### ISSUE TITLE
Smoke sprite stuck on screen

### ISSUE THREAD

**Issue by skepticalmartyr** [skepticalmartyr/PaperGorillas#93]
After continuous underwater building destruction on Nautilot, the smoke gets stuck on the screen.

<img width="331" alt="screen shot 2017-11-11 at 9 07 27 am" src="https://user-images.githubusercontent.com/13459311/32690164-04b86d24-c6c0-11e7-965f-abd4a0616183.png">

**Comment by skepticalmartyr** [comment]
Same thing happens with sparks. 
<img width="110" alt="screen shot 2017-11-11 at 9 36 40 am" src="https://user-images.githubusercontent.com/13459311/32690399-12ca068a-c6c4-11e7-9ed1-a86936ad1cb7.png">

**Comment by Saltallica** [comment]
decreasing the bubbles seems to have fixed this. STAY TUNED
